#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{spawnSync}=require('node:child_process');
const lib=require('./lib/project.cjs'),cli=path.join(__dirname,'content.cjs');
const {options}=lib.parse(process.argv.slice(2));
const base=options.project?path.resolve(options.project):path.join(lib.skillRoot,'.verification');
const folder=path.join(base,'system-smoke-'+new Date().toISOString().replaceAll(':','-')+'-'+crypto.randomBytes(3).toString('hex'));
fs.mkdirSync(folder,{recursive:true});
const project=path.join(folder,'empty-student'),tests=[];
function run(args,expected=0){const r=spawnSync(process.execPath,[cli,...args,'--project',project],{encoding:'utf8',env:{...process.env,NODE_PATH:''}});assert.equal(r.status,expected,r.stderr+' '+r.stdout);return r.stdout?JSON.parse(r.stdout):null;}
function json(name,data){const f=path.join(folder,name+'.json');fs.writeFileSync(f,JSON.stringify(data));return f;}
function test(name,fn){fn();tests.push({name,pass:true});}
function qa(id){return run(['qa','--id',id,'--file',json('qa-'+id,{reviewer:'fixture',viewed_actual_artifact:true,content_pass:true,media_pass:true})]);}
let story,carousel;
try{
 test('Fresh project and 30 Vietnamese commands',()=>{const r=run(['init']);assert.equal(r.brand_configured,false);assert.equal(run(['doctor']).commands,30);const map=lib.read(path.join(lib.skillRoot,'command-map.json'));assert.equal(new Set(map.commands.map(x=>x.alias)).size,30);assert(map.commands.some(x=>x.alias==='/vietbai'));assert(!map.commands.some(x=>x.alias==='/viet'));assert.equal(fs.readdirSync(path.join(project,'database')).length,10);});
 test('Setup checks only missing fields and preserves supplied profile',()=>{const initial=run(['profile']);assert.equal(initial.complete,false);assert(initial.missing.some(x=>x.field==='brand_name'));const f=json('brand',{brand_name:'Brand Fixture',target_audience:'Người quản lý',tone_of_voice:'Rõ ràng',founder:'Học viên giả lập'});let result=run(['setup','--file',f]);assert.equal(result.complete,false);assert(!result.missing.some(x=>['brand_name','target_audience','tone_of_voice'].includes(x.field)));result=run(['setup','--file',json('brand-rest',{products:[{name:'Khoá học quản lý',description:'Hướng dẫn phân quyền'}],usp:'Thực hành cùng mentor',content_goal:'Xây dựng uy tín'})]);assert.equal(result.complete,true);assert.deepEqual(result.missing,[]);run(['init']);assert.equal(lib.read(path.join(project,'database','brand_config.json')).brand_name,'Brand Fixture');assert.equal(run(['profile']).complete,true);});
 test('Strategy, sourced ideas, deduplication and template catalog',()=>{run(['strategy','--file',json('strategy',{content_pillars:[{name:'Quản lý',angles:['insight','story','system','result','reframe']}]})]);const f=json('ideas',[{topic:'Phân quyền',sources:[{type:'hypothetical',text:'Ví dụ giả định'}]}]);run(['ideas','--file',f]);run(['ideas','--file',f]);assert.equal(run(['ideas']).length,1);const t=run(['templates']);assert.ok(t.builtin);});
 test('Text and linked media preserve jobs and idea progress',()=>{const idea=run(['ideas'])[0];story=run(['new','--topic','Phân quyền','--format','story','--idea',idea.id]);fs.writeFileSync(path.join(story.folder,'caption.txt'),'Một ví dụ giả định về trao quyền.');fs.writeFileSync(path.join(story.folder,'master_content.md'),'Bản chữ gốc v1.');run(['update','--id',story.id,'--file',json('content',{big_idea:'Quyền hạn cần tiêu chí',sources:[{type:'hypothetical',text:'Ví dụ giả định'}]})]);qa(story.id);assert.equal(run(['validate','--id',story.id]).valid,true);assert.equal(run(['ideas'])[0].status,'PRODUCED');carousel=run(['new','--topic','Phân quyền','--format','carousel','--parent',story.id,'--idea',idea.id]);assert.equal(run(['list']).length,2);assert.equal(run(['show','--id',carousel.id]).parent_id,story.id);assert.equal(run(['ideas'])[0].status,'IN_PROGRESS');});
 test('Invalid update is atomic and does not overwrite status',()=>{const before=run(['show','--id',story.id]);run(['update','--id',story.id,'--file',json('bad-update',{big_idea:'Hacked',status:'PUBLISHED'})],1);assert.equal(run(['show','--id',story.id]).big_idea,before.big_idea);});
 test('Media-only approval cannot publish or schedule',()=>{run(['approve','--id',story.id,'--scope','media','--by','Fixture','--note','Duyệt media']);run(['published','--id',story.id,'--channel','fixture-channel','--url','https://example.com/fixture','--evidence','fixture-only'],1);run(['schedule','--id',story.id,'--channel','fixture-channel','--schedule-id','fixture','--at','2030-01-01T10:00:00+07:00','--evidence','fixture-only'],1);});
 test('Publish approval checks channel and content version',()=>{run(['approve','--id',story.id,'--scope','publish','--by','Fixture','--note','Duyệt fixture','--channel','fixture-channel']);run(['published','--id',story.id,'--channel','wrong-channel','--url','https://example.com/fixture','--evidence','fixture-only'],1);fs.appendFileSync(path.join(story.folder,'master_content.md'),' Đã thay đổi.');assert.equal(run(['validate','--id',story.id],2).valid,false);run(['published','--id',story.id,'--channel','fixture-channel','--url','https://example.com/fixture','--evidence','fixture-only'],1);qa(story.id);run(['approve','--id',story.id,'--scope','publish','--by','Fixture','--note','Duyệt bản sửa','--channel','fixture-channel']);assert.equal(run(['published','--id',story.id,'--channel','fixture-channel','--url','https://example.com/fixture','--evidence','fixture-only; no external posting']).status,'PUBLISHED');});
 test('Media required, artifact integrity and revision tracking',()=>{fs.writeFileSync(path.join(carousel.folder,'caption.txt'),'Carousel giả lập.');run(['update','--id',carousel.id,'--file',json('carousel-content',{big_idea:'Trao quyền',sources:[{type:'hypothetical',text:'Fixture'}]})]);qa(carousel.id);run(['validate','--id',carousel.id],2);const png=path.join(folder,'fixture.png');fs.writeFileSync(png,Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a4l8AAAAASUVORK5CYII=','base64'));run(['artifact','--id',carousel.id,'--path',png,'--role','slide-01']);qa(carousel.id);assert.equal(run(['validate','--id',carousel.id]).valid,true);const r=run(['show','--id',carousel.id]);fs.appendFileSync(path.join(carousel.folder,r.artifacts[0].file),'corrupt');run(['validate','--id',carousel.id],2);run(['artifact','--id',carousel.id,'--path',png,'--role','slide-01']);qa(carousel.id);assert.equal(run(['validate','--id',carousel.id]).valid,true);assert.equal(run(['show','--id',carousel.id]).artifacts.filter(a=>a.active).length,1);});
 test('Scheduled receipt must match approved channel and time',()=>{const at='2030-01-01T10:00:00+07:00';run(['approve','--id',carousel.id,'--scope','publish','--by','Fixture','--note','Duyệt lịch fixture','--channel','fixture-channel','--at',at]);run(['schedule','--id',carousel.id,'--channel','fixture-channel','--schedule-id','fixture','--at','2030-01-02T10:00:00+07:00','--evidence','fixture-only'],1);assert.equal(run(['schedule','--id',carousel.id,'--channel','fixture-channel','--schedule-id','fixture','--at',at,'--evidence','fixture-only; no external scheduling']).status,'SCHEDULED');});
 test('Current feedback does not become a permanent rule',()=>{run(['feedback','--id',story.id,'--text','Gọn hơn']);assert.equal(lib.read(path.join(project,'database','preferences.json')).length,0);run(['feedback','--id',story.id,'--text','Luôn xưng tôi/bạn','--scope','permanent','--by','Fixture']);assert.equal(lib.read(path.join(project,'database','preferences.json')).length,1);});
 test('Asset registry, editorial plans and verified channel metadata persist',()=>{const asset=path.join(folder,'fixture.png');run(['assets','--file',json('assets',{kind:'personal_image',path:asset,source:'student fixture'})]);assert.equal(run(['assets']).length,1);run(['plan','--file',json('plan',{topic:'Phân quyền',format:'carousel',planned_at:'2030-01-01T10:00:00+07:00'})]);assert.equal(run(['plan'])[0].status,'EDITORIAL_PLAN');run(['channels','--file',json('channel',{id:'fixture-channel',platform:'facebook',verification_evidence:'fixture only, no connection'})]);assert.equal(run(['channels']).length,1);});
 test('Output folders contain local caption, media and offline gallery',()=>{const result=run(['outputs','--id',carousel.id]);assert.equal(result.selected.caption,'Carousel giả lập.');assert.ok(result.selected.artifacts.some(a=>a.exists&&a.local_media));assert.ok(fs.existsSync(result.selected.preview));assert.ok(fs.existsSync(result.preview));assert.equal(result.selected.phone.local_path_accessible,false);const html=fs.readFileSync(result.selected.preview,'utf8');assert.match(html,/Carousel giả lập/);assert.match(html,/img loading/);assert.doesNotMatch(html,/<script/i);run(['open','--id',carousel.id],1);});
 const report={ok:true,tests,project,external_actions:false};lib.write(path.join(folder,'smoke-result.json'),report);process.stdout.write(JSON.stringify(report,null,2)+'\n');
}catch(e){const report={ok:false,tests,error:e.message,project,external_actions:false};lib.write(path.join(folder,'smoke-result.json'),report);process.stderr.write(JSON.stringify(report,null,2)+'\n');process.exitCode=1;}
